# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'player.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(777, 579)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.previous = QtWidgets.QPushButton(self.centralwidget)
        self.previous.setObjectName("previous")
        self.horizontalLayout_2.addWidget(self.previous)
        self.play = QtWidgets.QPushButton(self.centralwidget)
        self.play.setObjectName("play")
        self.horizontalLayout_2.addWidget(self.play)
        self.next = QtWidgets.QPushButton(self.centralwidget)
        self.next.setObjectName("next")
        self.horizontalLayout_2.addWidget(self.next)
        self.playlists = QtWidgets.QPushButton(self.centralwidget)
        self.playlists.setObjectName("playlists")
        self.horizontalLayout_2.addWidget(self.playlists)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.music_list = QtWidgets.QListWidget(self.centralwidget)
        self.music_list.setObjectName("music_list")
        self.verticalLayout.addWidget(self.music_list)
        self.add_music = QtWidgets.QPushButton(self.centralwidget)
        self.add_music.setObjectName("add_music")
        self.verticalLayout.addWidget(self.add_music)
        self.duration = QtWidgets.QSlider(self.centralwidget)
        self.duration.setMaximum(100)
        self.duration.setPageStep(20)
        self.duration.setTracking(True)
        self.duration.setOrientation(QtCore.Qt.Horizontal)
        self.duration.setObjectName("duration")
        self.verticalLayout.addWidget(self.duration)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.previous.setText(_translate("MainWindow", "|<"))
        self.play.setText(_translate("MainWindow", "|>"))
        self.next.setText(_translate("MainWindow", ">|"))
        self.playlists.setText(_translate("MainWindow", "Плейлисты"))
        self.add_music.setText(_translate("MainWindow", "Добавить трек"))
